# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noven/Projects/PythonGui/src/ui/AccountBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountBlock(object):
    def setupUi(self, AccountBlock):
        AccountBlock.setObjectName("AccountBlock")
        AccountBlock.resize(350, 105)
        AccountBlock.setMinimumSize(QtCore.QSize(350, 105))
        self.twoFactorCode = QtWidgets.QLabel(AccountBlock)
        self.twoFactorCode.setGeometry(QtCore.QRect(0, 40, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.twoFactorCode.setFont(font)
        self.twoFactorCode.setLineWidth(0)
        self.twoFactorCode.setAlignment(QtCore.Qt.AlignCenter)
        self.twoFactorCode.setObjectName("twoFactorCode")
        self.account = QtWidgets.QLabel(AccountBlock)
        self.account.setGeometry(QtCore.QRect(10, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.account.setFont(font)
        self.account.setLineWidth(0)
        self.account.setAlignment(QtCore.Qt.AlignCenter)
        self.account.setObjectName("account")
        self.copyCode = QtWidgets.QPushButton(AccountBlock)
        self.copyCode.setGeometry(QtCore.QRect(200, 60, 113, 32))
        self.copyCode.setObjectName("copyCode")
        self.showConfirmationButtom = QtWidgets.QPushButton(AccountBlock)
        self.showConfirmationButtom.setGeometry(QtCore.QRect(200, 15, 113, 32))
        self.showConfirmationButtom.setObjectName("showConfirmationButtom")

        self.retranslateUi(AccountBlock)
        QtCore.QMetaObject.connectSlotsByName(AccountBlock)

    def retranslateUi(self, AccountBlock):
        _translate = QtCore.QCoreApplication.translate
        AccountBlock.setWindowTitle(_translate("AccountBlock", "Form"))
        self.twoFactorCode.setText(_translate("AccountBlock", "92FKX"))
        self.account.setText(_translate("AccountBlock", "qq1411348107"))
        self.copyCode.setText(_translate("AccountBlock", "复制代码"))
        self.showConfirmationButtom.setText(_translate("AccountBlock", "待确认报价"))
