# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noven/Projects/PythonGui/src/ui/AccountBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountBlock(object):
    def setupUi(self, AccountBlock):
        AccountBlock.setObjectName("AccountBlock")
        AccountBlock.resize(302, 144)
        self.showConfirmationButtom = QtWidgets.QPushButton(AccountBlock)
        self.showConfirmationButtom.setGeometry(QtCore.QRect(180, 40, 91, 81))
        self.showConfirmationButtom.setObjectName("showConfirmationButtom")
        self.twoFactorCode = QtWidgets.QTextBrowser(AccountBlock)
        self.twoFactorCode.setGeometry(QtCore.QRect(30, 40, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.twoFactorCode.setFont(font)
        self.twoFactorCode.setObjectName("twoFactorCode")
        self.account = QtWidgets.QTextBrowser(AccountBlock)
        self.account.setGeometry(QtCore.QRect(30, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.account.setFont(font)
        self.account.setObjectName("account")

        self.retranslateUi(AccountBlock)
        QtCore.QMetaObject.connectSlotsByName(AccountBlock)

    def retranslateUi(self, AccountBlock):
        _translate = QtCore.QCoreApplication.translate
        AccountBlock.setWindowTitle(_translate("AccountBlock", "Form"))
        self.showConfirmationButtom.setText(_translate("AccountBlock", "获取报价"))
