# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noven/Projects/PythonGui/src/ui/ConfirmationBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmationBlock(object):
    def setupUi(self, ConfirmationBlock):
        ConfirmationBlock.setObjectName("ConfirmationBlock")
        ConfirmationBlock.resize(340, 80)
        ConfirmationBlock.setMinimumSize(QtCore.QSize(340, 80))
        self.verticalLayoutWidget = QtWidgets.QWidget(ConfirmationBlock)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.avatar = QtWidgets.QWidget(self.widget)
        self.avatar.setGeometry(QtCore.QRect(20, 12, 51, 51))
        self.avatar.setObjectName("avatar")
        self.confirm = QtWidgets.QPushButton(self.widget)
        self.confirm.setGeometry(QtCore.QRect(229, 7, 91, 32))
        self.confirm.setObjectName("confirm")
        self.cancel = QtWidgets.QPushButton(self.widget)
        self.cancel.setGeometry(QtCore.QRect(229, 37, 91, 32))
        self.cancel.setObjectName("cancel")
        self.registerDate = QtWidgets.QLabel(self.widget)
        self.registerDate.setGeometry(QtCore.QRect(80, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.registerDate.setFont(font)
        self.registerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.registerDate.setObjectName("registerDate")
        self.confirmRes = QtWidgets.QWidget(self.widget)
        self.confirmRes.setGeometry(QtCore.QRect(230, 16, 101, 41))
        self.confirmRes.setObjectName("confirmRes")
        self.confirmRes.raise_()
        self.avatar.raise_()
        self.confirm.raise_()
        self.cancel.raise_()
        self.registerDate.raise_()
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(ConfirmationBlock)
        QtCore.QMetaObject.connectSlotsByName(ConfirmationBlock)

    def retranslateUi(self, ConfirmationBlock):
        _translate = QtCore.QCoreApplication.translate
        ConfirmationBlock.setWindowTitle(_translate("ConfirmationBlock", "Form"))
        self.confirm.setText(_translate("ConfirmationBlock", "确认报价"))
        self.cancel.setText(_translate("ConfirmationBlock", "取消报价"))
        self.registerDate.setText(_translate("ConfirmationBlock", "XXXX-XX-XX"))
