# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noven/Projects/PythonGui/src/ui/ConfirmationBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmationBlock(object):
    def setupUi(self, ConfirmationBlock):
        ConfirmationBlock.setObjectName("ConfirmationBlock")
        ConfirmationBlock.resize(403, 120)
        self.verticalLayoutWidget = QtWidgets.QWidget(ConfirmationBlock)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 341, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.avatar = QtWidgets.QWidget(self.widget)
        self.avatar.setGeometry(QtCore.QRect(20, 10, 51, 51))
        self.avatar.setObjectName("avatar")
        self.confirm = QtWidgets.QPushButton(self.widget)
        self.confirm.setGeometry(QtCore.QRect(220, 10, 91, 32))
        self.confirm.setObjectName("confirm")
        self.cancel = QtWidgets.QPushButton(self.widget)
        self.cancel.setGeometry(QtCore.QRect(220, 40, 91, 32))
        self.cancel.setObjectName("cancel")
        self.registerDate = QtWidgets.QLabel(self.widget)
        self.registerDate.setGeometry(QtCore.QRect(90, 10, 131, 51))
        self.registerDate.setObjectName("registerDate")
        self.confirmRes = QtWidgets.QWidget(self.widget)
        self.confirmRes.setGeometry(QtCore.QRect(210, 20, 121, 41))
        self.confirmRes.setObjectName("confirmRes")
        self.confirmRes.raise_()
        self.avatar.raise_()
        self.confirm.raise_()
        self.cancel.raise_()
        self.registerDate.raise_()
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(ConfirmationBlock)
        QtCore.QMetaObject.connectSlotsByName(ConfirmationBlock)

    def retranslateUi(self, ConfirmationBlock):
        _translate = QtCore.QCoreApplication.translate
        ConfirmationBlock.setWindowTitle(_translate("ConfirmationBlock", "Form"))
        self.confirm.setText(_translate("ConfirmationBlock", "确认报价"))
        self.cancel.setText(_translate("ConfirmationBlock", "取消报价"))
        self.registerDate.setText(_translate("ConfirmationBlock", "XXXX-XX-XX"))
