# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\Files\vscode project\PythonSteamConfirm\src\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountList(object):
    def setupUi(self, AccountList):
        AccountList.setObjectName("AccountList")
        AccountList.resize(534, 565)
        self.centralwidget = QtWidgets.QWidget(AccountList)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 20, 421, 491))
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        AccountList.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AccountList)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 23))
        self.menubar.setObjectName("menubar")
        AccountList.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AccountList)
        self.statusbar.setObjectName("statusbar")
        AccountList.setStatusBar(self.statusbar)

        self.retranslateUi(AccountList)
        QtCore.QMetaObject.connectSlotsByName(AccountList)

    def retranslateUi(self, AccountList):
        _translate = QtCore.QCoreApplication.translate
        AccountList.setWindowTitle(_translate("AccountList", "MainWindow"))
